/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IYuzuKeeper } from "../IYuzuKeeper";

export class IYuzuKeeper__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IYuzuKeeper {
    return new Contract(address, _abi, signerOrProvider) as IYuzuKeeper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestForYUZU",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
