/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface HalfAttenuationZooRewardInterface extends ethers.utils.Interface {
  functions: {
    "blockNumberOfHalfAttenuationCycle()": FunctionFragment;
    "getZooBetweenBlocks(uint256,uint256)": FunctionFragment;
    "getZooFromStartblock(uint256,uint256,uint256,uint256)": FunctionFragment;
    "startBlock()": FunctionFragment;
    "zooPerBlock()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "blockNumberOfHalfAttenuationCycle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getZooBetweenBlocks",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getZooFromStartblock",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "startBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "zooPerBlock",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "blockNumberOfHalfAttenuationCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZooBetweenBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getZooFromStartblock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zooPerBlock",
    data: BytesLike
  ): Result;

  events: {};
}

export class HalfAttenuationZooReward extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: HalfAttenuationZooRewardInterface;

  functions: {
    blockNumberOfHalfAttenuationCycle(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "blockNumberOfHalfAttenuationCycle()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getZooBetweenBlocks(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getZooBetweenBlocks(uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getZooFromStartblock(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getZooFromStartblock(uint256,uint256,uint256,uint256)"(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    startBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "startBlock()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    zooPerBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "zooPerBlock()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  blockNumberOfHalfAttenuationCycle(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "blockNumberOfHalfAttenuationCycle()"(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getZooBetweenBlocks(
    _from: BigNumberish,
    _to: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getZooBetweenBlocks(uint256,uint256)"(
    _from: BigNumberish,
    _to: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getZooFromStartblock(
    _startBlock: BigNumberish,
    _blockNumberOfHalfAttenuationCycle: BigNumberish,
    _zooPerBlock: BigNumberish,
    _to: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getZooFromStartblock(uint256,uint256,uint256,uint256)"(
    _startBlock: BigNumberish,
    _blockNumberOfHalfAttenuationCycle: BigNumberish,
    _zooPerBlock: BigNumberish,
    _to: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  startBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "startBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  zooPerBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "zooPerBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    blockNumberOfHalfAttenuationCycle(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "blockNumberOfHalfAttenuationCycle()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZooBetweenBlocks(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZooBetweenBlocks(uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZooFromStartblock(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZooFromStartblock(uint256,uint256,uint256,uint256)"(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "startBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    zooPerBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "zooPerBlock()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    blockNumberOfHalfAttenuationCycle(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "blockNumberOfHalfAttenuationCycle()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZooBetweenBlocks(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZooBetweenBlocks(uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getZooFromStartblock(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getZooFromStartblock(uint256,uint256,uint256,uint256)"(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    startBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "startBlock()"(overrides?: CallOverrides): Promise<BigNumber>;

    zooPerBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "zooPerBlock()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    blockNumberOfHalfAttenuationCycle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "blockNumberOfHalfAttenuationCycle()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZooBetweenBlocks(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getZooBetweenBlocks(uint256,uint256)"(
      _from: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getZooFromStartblock(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getZooFromStartblock(uint256,uint256,uint256,uint256)"(
      _startBlock: BigNumberish,
      _blockNumberOfHalfAttenuationCycle: BigNumberish,
      _zooPerBlock: BigNumberish,
      _to: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    startBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "startBlock()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    zooPerBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "zooPerBlock()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
