/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IYuzuKeeperInterface extends ethers.utils.Interface {
  functions: {
    "requestForYUZU(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "requestForYUZU",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestForYUZU",
    data: BytesLike
  ): Result;

  events: {};
}

export class IYuzuKeeper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IYuzuKeeperInterface;

  functions: {
    requestForYUZU(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "requestForYUZU(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  requestForYUZU(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "requestForYUZU(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    requestForYUZU(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requestForYUZU(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    requestForYUZU(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "requestForYUZU(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    requestForYUZU(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "requestForYUZU(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
