/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MultiExecInterface extends ethers.utils.Interface {
  functions: {
    "exec(tuple[])": FunctionFragment;
    "owner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "exec",
    values: [{ to: string; value: BigNumberish; data: BytesLike }[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "exec", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;

  events: {};
}

export class MultiExec extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MultiExecInterface;

  functions: {
    exec(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "exec(tuple[])"(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;
  };

  exec(
    calls: { to: string; value: BigNumberish; data: BytesLike }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "exec(tuple[])"(
    calls: { to: string; value: BigNumberish; data: BytesLike }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    exec(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "exec(tuple[])"(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    exec(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "exec(tuple[])"(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    exec(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "exec(tuple[])"(
      calls: { to: string; value: BigNumberish; data: BytesLike }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
